/* Temperatures */

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_01` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_02` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_03` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_04` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_05` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_06` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_07` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_08` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_09` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_10` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_11` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_temperatures_2023_12` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Temperature` FLOAT UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

/* Relays */

CREATE TABLE IF NOT EXISTS `history_relays_2023_01` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_02` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_03` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_04` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_05` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_06` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_07` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_08` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_09` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_10` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_11` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_relays_2023_12` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Relay` TINYINT(3) UNSIGNED NOT NULL,
	`Error` TINYINT(3) UNSIGNED NOT NULL,
	`Vin` FLOAT NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

/* Heating */

CREATE TABLE IF NOT EXISTS `history_heating_2023_01` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_02` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_03` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_04` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_05` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_06` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_07` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_08` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_09` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_10` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_11` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `history_heating_2023_12` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Dt` DATETIME NOT NULL,
	`Address` INT(10) UNSIGNED NOT NULL,
	`Segment` TINYINT(3) UNSIGNED NOT NULL,
	`Mode` ENUM('Off','Auto','Manual') NOT NULL DEFAULT 'Off' COLLATE 'utf8_general_ci',
	`SettingTemperature` FLOAT NOT NULL DEFAULT '0',
	`Relay` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Dt` (`Dt`) USING BTREE,
	INDEX `Address` (`Address`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
